//go:build benchmark

package bench

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/lvcas-dotcom/pgfathom/internal/buildinfo"
	"github.com/lvcas-dotcom/pgfathom/internal/model"
)

// Two files, because they age differently. Recall is a property of the tool
// and the corpus: same inputs, same numbers, and a diff means something
// changed. Cost is a property of the machine that ran it, and pinning that to
// a golden would be pinning somebody's laptop.
//
// Both are written in English: they are published material, linked from the
// README, and the convention puts what the public reads in English.
const (
	FileRecall = "recall.md"
	FileCost   = "cost.md"
)

// Skipped is a manifest entry this run could not measure, and why.
//
// It exists because the alternative is worse than it looks. A schema the
// harness cannot reach simply produces no section, and the regenerated file
// reads as complete — the reader has no way to tell a corpus of two from a
// corpus of three measured on a machine that held two. Whoever runs
// `make benchmark` without the optional local dump would republish the file
// with a row silently deleted, and the deletion is invisible in review unless
// somebody diffs against a copy they happened to remember.
//
// The manifest already promised this: "presente na máquina, é medido; ausente,
// o relatório diz que não foi" (bench/corpus.toml). It was said to the test
// log, which the published document does not carry.
type Skipped struct {
	Name   string
	Reason string
}

// WriteReports renders both files under docs/benchmark.
func WriteReports(results []EntryResult, skipped []Skipped, elapsed time.Duration) error {
	dir := filepath.Join(repoRoot(), "docs", "benchmark")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating report directory: %w", err)
	}

	for name, content := range map[string]string{
		FileRecall: renderRecall(results, skipped),
		FileCost:   renderCost(results, elapsed),
	} {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

func renderRecall(results []EntryResult, skipped []Skipped) string {
	var b strings.Builder

	b.WriteString("# Recovery rate on the corpus\n\n")
	b.WriteString("Generated by `make benchmark`. Do not edit by hand.\n\n")
	b.WriteString("The procedure is the same for every schema: load it, read the declared foreign\n")
	b.WriteString("keys, drop all of them, and ask the tool how many come back. The ground truth is\n")
	b.WriteString("read by the harness's own query rather than through the catalog reader being\n")
	b.WriteString("measured: a bug there would drop a key from the numerator and the denominator at\n")
	b.WriteString("once, and the recall would look perfect for the wrong reason.\n\n")

	b.WriteString("**No verdict is measured here.** The public corpus is DDL without a single row,\n")
	b.WriteString("so nothing can be confirmed or broken. What these tables measure is whether the\n")
	b.WriteString("right candidate was *raised*. The rule that no false positive may be confirmed\n")
	b.WriteString("lives with the integration fixtures, where the answer was built alongside the\n")
	b.WriteString("scenario and a wrong confirmation is recognisable as wrong.\n\n")

	b.WriteString("**Every schema is measured in two regimes, and they answer different\n")
	b.WriteString("questions.** In *partial*, half the declared keys are removed and recovery is\n")
	b.WriteString("scored on that half; the half left behind is evidence, which naming detection\n")
	b.WriteString("reads exactly as it would in a database that declared part of its integrity and\n")
	b.WriteString("forgot the rest. That is the ordinary case, and the one a user is in. In\n")
	b.WriteString("*greenfield* the rest goes too, and recovery is scored on everything: the\n")
	b.WriteString("hardest case, a database that declares nothing.\n\n")
	b.WriteString("Reading only greenfield understates the tool, and by a lot where it matters\n")
	b.WriteString("most. Detection learns the local reference affix from declared keys; with none\n")
	b.WriteString("declared it has nothing to learn from, and a schema whose convention no shipped\n")
	b.WriteString("profile knows falls to almost nothing. Reading only partial would hide the\n")
	b.WriteString("hardest case. Both are published, and each row says which it is.\n\n")

	fmt.Fprintf(&b, "Tool `%s`.\n\n", version())

	if len(skipped) > 0 {
		b.WriteString("**Not measured on this run.** The manifest names schemas this machine\n")
		b.WriteString("could not reach, so the sections below are the corpus minus these. A file\n")
		b.WriteString("regenerated without them is not a smaller corpus; it is the same corpus,\n")
		b.WriteString("partly measured.\n\n")
		for _, s := range skipped {
			fmt.Fprintf(&b, "- `%s` — %s\n", s.Name, s.Reason)
		}
		b.WriteString("\n")
	}

	for _, r := range results {
		fmt.Fprintf(&b, "## %s\n\n", r.Entry.Name)

		if r.Entry.Note != "" {
			fmt.Fprintf(&b, "%s\n\n", r.Entry.Note)
		}

		fmt.Fprintf(&b, "PostgreSQL %s · profile `%s` · %d tables · **%d keys in the truth set**",
			r.ServerVersion, r.Entry.Profile, r.Tables, r.Truth)
		if r.Entry.Schema != DefaultSchema {
			fmt.Fprintf(&b, " · schema `%s`", r.Entry.Schema)
		}
		if r.TruthComposite > 0 {
			fmt.Fprintf(&b, ", %d of them composite", r.TruthComposite)
		}
		if r.OutOfScope > 0 {
			fmt.Fprintf(&b, " · %d keys reach outside the measured schema and are excluded", r.OutOfScope)
		}
		if r.Entry.Commit != "" {
			fmt.Fprintf(&b, " · commit `%s`", short(r.Entry.Commit))
		}
		b.WriteString("\n\n")

		if r.LoadFailures > 0 {
			fmt.Fprintf(&b, "**%d statements of this dump did not apply** — a dump taken from a live "+
				"database names roles, schemas and extensions that a throwaway server does not have. "+
				"The numbers below describe what loaded.\n\n", r.LoadFailures)
		}

		b.WriteString("| Regime | Configuration | Recovered | Recall | of which composite | Candidates | Outside the truth set |\n")
		b.WriteString("|---|---|---:|---:|---:|---:|---:|\n")

		for _, m := range r.Measurements {
			fmt.Fprintf(&b, "| %s | %s | %d of %d | %.1f%% | %d of %d | %d | %d |\n",
				m.Regime, m.Config, m.Recovered, m.Truth, 100*m.Recall(),
				m.RecoveredComposite, r.TruthComposite, m.Candidates, m.Unmatched)
		}
		b.WriteString("\n")

		b.WriteString("Candidates outside the truth set are **not false positives**. In a real schema\n")
		b.WriteString("a true relationship that was never declared is this tool's product; counting it\n")
		b.WriteString("as a defect would publish as an error the very thing being delivered.\n\n")

		writeCoverageNote(&b, r)
	}

	return b.String()
}

func writeCoverageNote(b *strings.Builder, r EntryResult) {
	if len(r.Measurements) == 0 {
		return
	}
	c := r.Measurements[len(r.Measurements)-1].Coverage

	if c.TablesAnalyzed == c.TablesTotal && len(c.TablesUnsupported) == 0 {
		fmt.Fprintf(b, "All %d tables in scope were analysed.\n\n", c.TablesTotal)
		return
	}

	fmt.Fprintf(b, "Coverage: %d of %d tables analysed (%.0f%%).",
		c.TablesAnalyzed, c.TablesTotal, 100*c.AnalyzedShare())

	reasons := make(map[model.UnsupportedReason]int)
	for _, s := range c.TablesUnsupported {
		reasons[s.Reason]++
	}
	for _, reason := range []model.UnsupportedReason{
		model.ReasonNoPrimaryKey, model.ReasonPartitioned, model.ReasonInheritance,
	} {
		if n := reasons[reason]; n > 0 {
			fmt.Fprintf(b, " %d %s.", n, reason)
		}
	}
	b.WriteString("\n\n")
}

func renderCost(results []EntryResult, elapsed time.Duration) string {
	var b strings.Builder

	b.WriteString("# Cost per stage\n\n")
	b.WriteString("Generated by `make benchmark`. Do not edit by hand.\n\n")
	b.WriteString("These numbers describe the machine that ran them as much as the tool. They are\n")
	b.WriteString("good for comparing stages against each other, and runs on one machine against\n")
	b.WriteString("each other; they are not a performance promise. That is why they live outside\n")
	b.WriteString("the recall file, which is stable across runs.\n\n")

	fmt.Fprintf(&b, "Tool `%s` · %s/%s · %d CPUs · whole run in %s.\n\n",
		version(), runtime.GOOS, runtime.GOARCH, runtime.NumCPU(), elapsed.Round(time.Second))

	for _, r := range results {
		fmt.Fprintf(&b, "## %s\n\n", r.Entry.Name)

		for _, m := range r.Measurements {
			fmt.Fprintf(&b, "### %s — %s\n\n", m.Config, m.Duration.Round(time.Millisecond))

			b.WriteString("| Stage | Time |\n|---|---:|\n")
			for _, s := range m.Stages {
				fmt.Fprintf(&b, "| %s | %s |\n", s.Stage, s.Duration.Round(time.Millisecond))
			}
			b.WriteString("\n")

			writeFunnel(&b, m.Coverage)

			for _, w := range m.Warnings {
				fmt.Fprintf(&b, "- warning: %s\n", w)
			}
			if len(m.Warnings) > 0 {
				b.WriteString("\n")
			}
		}
	}

	return b.String()
}

// writeFunnel is the account of what happened to every candidate. Checked
// minus rejected is what reaches an anti-join, and that is the number saying
// what this tool costs the server it is pointed at.
func writeFunnel(b *strings.Builder, c model.Coverage) {
	b.WriteString("| Funnel | |\n|---|---:|\n")
	fmt.Fprintf(b, "| raised | %d |\n", c.CandidatesFound)

	if c.StatsPrefilter {
		fmt.Fprintf(b, "| checked by the prefilter | %d |\n", c.CandidatesStatsChecked)
		fmt.Fprintf(b, "| rejected by the prefilter | %d |\n", c.CandidatesStatsRejected)
		fmt.Fprintf(b, "| without statistics | %d |\n", c.CandidatesWithoutStats)
	} else {
		b.WriteString("| prefilter | off |\n")
	}

	fmt.Fprintf(b, "| validation queries | %d |\n", c.CandidatesValidated+c.CandidatesTimedOut)
	fmt.Fprintf(b, "| hit the time ceiling | %d |\n", c.CandidatesTimedOut)
	b.WriteString("\n")
}

func version() string {
	if buildinfo.Version == "" {
		return "dev"
	}
	return buildinfo.Version
}

func short(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}
