//go:build ignore

// termsvg renders coloured terminal output as an SVG, so the README can show
// what the tool actually prints.
//
// It exists because the alternative is a screenshot: a PNG nobody can diff,
// that goes stale silently, and that a maintainer cannot regenerate without the
// same machine and the same font. This reads the real bytes the tool emits —
// escape sequences included — and the result is regenerated by `make demo-svg`
// whenever the report format changes.
//
// Built with `//go:build ignore` and run through `go run`: it is a maintainer's
// tool, and it has no business in the binary anyone installs.
//
//	pgfathom discover --color always | go run scripts/termsvg.go > assets/demo.svg
package main

import (
	"bufio"
	"fmt"
	"html"
	"os"
	"strconv"
	"strings"
)

// Terminal metrics. The advance width is the one number that has to be right:
// too small and glyphs overlap, too large and the box columns drift apart.
// 0.6 em is the ratio every monospace face in the fallback list holds.
const (
	fontSize   = 14.0
	lineHeight = 20.0
	charWidth  = fontSize * 0.6
	padX       = 22.0
	padY       = 18.0
	titleBar   = 34.0
)

// The window, in the same palette the report itself uses. Dark on purpose: the
// brand's red and aqua are chosen against a dark terminal, which is what the
// people who run this tool are looking at.
const (
	background = "#1a1614"
	foreground = "#ddd5d0"
	chromeBar  = "#231e1b"
)

type style struct {
	colour string
	bold   bool
	dim    bool
}

// span is a run of characters sharing one style.
type span struct {
	text  string
	style style
}

func main() {
	lines, width := read(os.Stdin)

	w := padX*2 + float64(width)*charWidth
	h := titleBar + padY*2 + float64(len(lines))*lineHeight

	out := bufio.NewWriter(os.Stdout)
	defer func() { _ = out.Flush() }()

	fmt.Fprintf(out, `<svg xmlns="http://www.w3.org/2000/svg" width="%.0f" height="%.0f" viewBox="0 0 %.0f %.0f" font-family="ui-monospace,SFMono-Regular,Menlo,Consolas,'DejaVu Sans Mono',monospace" font-size="%.0f">`,
		w, h, w, h, fontSize)

	fmt.Fprintf(out, `<rect width="%.0f" height="%.0f" rx="10" fill="%s"/>`, w, h, background)
	fmt.Fprintf(out, `<path d="M0 10a10 10 0 0 1 10-10h%.0fa10 10 0 0 1 10 10v%.0fH0Z" fill="%s"/>`,
		w-20, titleBar-10, chromeBar)
	for i, dot := range []string{"#e2483d", "#8c7d73", "#7ec9b8"} {
		fmt.Fprintf(out, `<circle cx="%.0f" cy="17" r="5" fill="%s"/>`, 20+float64(i)*18, dot)
	}

	for i, spans := range lines {
		y := titleBar + padY + float64(i)*lineHeight + fontSize*0.8
		col := 0.0

		for _, s := range spans {
			if strings.TrimSpace(s.text) != "" {
				fmt.Fprintf(out, `<text x="%.1f" y="%.1f" fill="%s"`, padX+col*charWidth, y, s.style.paint())
				if s.style.bold {
					fmt.Fprint(out, ` font-weight="600"`)
				}
				if s.style.dim {
					fmt.Fprint(out, ` opacity="0.62"`)
				}
				// xml:space keeps the leading run of spaces that carries the
				// report's indentation; without it the whole layout collapses.
				fmt.Fprintf(out, ` xml:space="preserve">%s</text>`, html.EscapeString(s.text))
			}
			col += float64(len([]rune(s.text)))
		}
	}

	fmt.Fprint(out, `</svg>`)
}

func (s style) paint() string {
	if s.colour != "" {
		return s.colour
	}
	return foreground
}

// read consumes ANSI-coloured text and returns styled spans per line, plus the
// widest line in characters.
func read(f *os.File) ([][]span, int) {
	var lines [][]span
	widest := 0

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for sc.Scan() {
		spans, width := parse(sc.Text())
		lines = append(lines, spans)
		if width > widest {
			widest = width
		}
	}
	return lines, widest
}

func parse(line string) ([]span, int) {
	var (
		spans []span
		cur   style
		buf   strings.Builder
		width int
	)

	flush := func() {
		if buf.Len() > 0 {
			spans = append(spans, span{text: buf.String(), style: cur})
			buf.Reset()
		}
	}

	for i := 0; i < len(line); {
		if line[i] != 0x1b {
			r := line[i]
			buf.WriteByte(r)
			if r < 0x80 || r >= 0xc0 { // count runes, not bytes
				width++
			}
			i++
			continue
		}

		end := strings.IndexByte(line[i:], 'm')
		if end < 0 {
			break
		}
		flush()
		cur = apply(cur, line[i+2:i+end])
		i += end + 1
	}

	flush()
	return spans, width
}

// apply folds one escape sequence's parameters into the running style. Only the
// attributes this report emits are handled; anything else is ignored rather
// than guessed at.
func apply(s style, params string) style {
	fields := strings.Split(params, ";")

	for i := 0; i < len(fields); i++ {
		switch fields[i] {
		case "", "0":
			s = style{}
		case "1":
			s.bold = true
		case "2":
			s.dim = true
		case "31":
			s.colour = "#e2483d"
		case "33":
			s.colour = "#d9a441"
		case "36":
			s.colour = "#7ec9b8"
		case "38":
			// 38;2;R;G;B — the brand colours, when the terminal has them.
			if i+4 < len(fields) && fields[i+1] == "2" {
				r, _ := strconv.Atoi(fields[i+2])
				g, _ := strconv.Atoi(fields[i+3])
				b, _ := strconv.Atoi(fields[i+4])
				s.colour = fmt.Sprintf("#%02x%02x%02x", r, g, b)
				i += 4
			}
		}
	}
	return s
}
